from .region import Region
from .provincia import Provincia
from .comuna import Comuna
from .categoria import Categoria
from .usuario import Usuario
from .proyecto import Proyecto
from .documento import Documento
from .log_cambios import LogCambio  
from .pavimento import Pavimento
from .ciclovia import Ciclovia
from .parque import Parque
from .estado_avance import EstadoAvance
from .tipo_calzada import TipoCalzada
from .tipo_pavimento import TipoPavimento
from .tipo_ciclovia import TipoCiclovia
from .contratista import Contratista
from .fuente_financiamiento import FuenteFinanciamiento
